version: "3.8"
services:
  db:
    image: postgres:16
    container_name: hawkstead_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hawkstead_net

volumes:
  postgres_data:

networks:
  hawkstead_net: